from src.problem_domain.base_problem import BaseProblem
from src.problem_domain.com_influence_max_problem import ComInfluenceMaxProblem
from src.problem_domain.compiler_args_selection_problem import CompilerArgsSelectionProblem
from src.problem_domain.contamination_problem import ContaminationProblem
from src.problem_domain.surrogate_problem import SurrogateProblem
